### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by cmeeren** [elmish/Uil#5]
This repo has not seen any activity for over 4 months. Is it left for dead? Are there any other projects working on creating a dynamic UI DSL for WPF?

**Comment by Lleutch** [comment]
Hi, 

It has been left on the side, for a bit, and I have still left it, right now for some personal reasons. That is why there hasn't been any activity on it for the past 4 months.
I hope, I won't leave it for dead, because I do believe that such project could be good to pursue...
Now to answer, I will get back to work on it, I cannot give an answer now, but surely, it won't be right now. 

Now, regarding the fact if there is any other project working on creating a dynamic UI DSL for WPF, I can't answer that (new might have come up in the mean-time).

I hope it does answer your question 😄

**Comment by cmeeren** [comment]
Thanks! Yes, that surely answers the question. Best of wishes for whatever is going on. :)
